"""Hermes Agent (Nous Research) runner.

Hermes is a CLI agent runtime (`pip install hermes-agent`) that runs its own
autonomous tool loop. Seraph drives it headlessly on the backend host, pointed at
the user's Ollama for the model, with smart approvals + a confined working dir.

This module prepares a per-run, isolated Hermes home (so memory/skills stay scoped
to the engagement) and assembles the streamed command. Execution + streaming is
handled by the /ws/hermes/{scan_id} route via services.executor.
"""
import os
import shlex
import shutil
import subprocess
from typing import Optional

from sqlalchemy.orm import Session

from database import AppSetting, Finding, Scan, Target

# Root for per-run Hermes homes + workspaces.
_HERMES_ROOT = os.path.expanduser("~/.seraph/hermes")


# ── AppSetting helpers ────────────────────────────────────────────────────────

def get_setting(db: Session, key: str, default: str = "") -> str:
    row = db.query(AppSetting).filter(AppSetting.key == key).first()
    return row.value if row else default


def set_setting(db: Session, key: str, value: str) -> None:
    row = db.query(AppSetting).filter(AppSetting.key == key).first()
    if row:
        row.value = value
    else:
        db.add(AppSetting(key=key, value=value))


# ── Availability ──────────────────────────────────────────────────────────────

def hermes_path() -> Optional[str]:
    return shutil.which("hermes")


def hermes_available() -> bool:
    return hermes_path() is not None


def hermes_version() -> str:
    path = hermes_path()
    if not path:
        return ""
    try:
        out = subprocess.run([path, "--version"], capture_output=True, text=True, timeout=10)
        return (out.stdout or out.stderr or "").strip().splitlines()[0] if (out.stdout or out.stderr) else ""
    except Exception:
        return ""


# ── Per-run config / prompt ───────────────────────────────────────────────────

_MODE_PERSONA = {
    "attack": "You are an expert penetration tester on an AUTHORIZED red-team engagement. "
              "Enumerate, find vulnerabilities, and exploit them to demonstrate impact. Escalate "
              "privileges where possible and map every viable attack path.",
    "recon": "You are a security researcher performing AUTHORIZED reconnaissance. Map the attack "
             "surface — open ports, services, versions, users, subdomains. Do NOT exploit, brute-force, "
             "or disrupt anything. Discovery and enumeration only.",
    "audit": "You are a security auditor performing an AUTHORIZED assessment. Identify, verify, and "
             "document vulnerabilities and misconfigurations WITHOUT exploiting them. Note a severity "
             "(Critical/High/Medium/Low) and a short remediation for each finding.",
}


def _yaml_escape(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _write_config(home: str, run_dir: str, model: str, ollama_url: str,
                  allow_private_urls: bool, sandbox: bool) -> None:
    """Write ~/.hermes/config.yaml under the per-run HOME."""
    cfg_dir = os.path.join(home, ".hermes")
    os.makedirs(cfg_dir, exist_ok=True)
    base_url = ollama_url.rstrip("/") + "/v1"  # Ollama's OpenAI-compatible endpoint
    terminal_backend = "docker" if sandbox else "local"

    config = f"""# Generated by Seraph — per-engagement Hermes config.
model:
  default: {_yaml_escape(model)}
  provider: "openai"
  base_url: {_yaml_escape(base_url)}
providers:
  openai:
    api_key: "ollama"
    base_url: {_yaml_escape(base_url)}
approvals:
  mode: "smart"
  timeout: 60
  cron_mode: "deny"
terminal:
  backend: {_yaml_escape(terminal_backend)}
  cwd: {_yaml_escape(run_dir)}
security:
  allow_private_urls: {"true" if allow_private_urls else "false"}
  allow_lazy_installs: false
  tirith_enabled: true
display:
  interface: "cli"
  streaming: true
"""
    with open(os.path.join(cfg_dir, "config.yaml"), "w") as f:
        f.write(config)


def _build_task(target: Target, findings: list[Finding], mode: str) -> str:
    persona = _MODE_PERSONA.get(mode, _MODE_PERSONA["attack"])
    host = target.hostname_or_ip
    ttype = (target.target_type or "host").replace("_", " ")
    ports = target.ports or "unknown — discover them"

    if findings:
        fl = "\n".join(
            f"  - [{f.severity.upper()}] {f.title}" + (f" ({f.cve_id})" if f.cve_id else "")
            for f in findings[:20]
        )
    else:
        fl = "  None yet."

    return f"""{persona}

ENGAGEMENT TARGET:
  Host: {host}
  Type: {ttype}
  Known ports/services: {ports}

EXISTING FINDINGS (from prior Seraph scans):
{fl}

RULES:
  1. SCOPE: Only interact with {host}. Never touch any other host, network, or external system.
  2. You run inside a confined working directory; keep all files there.
  3. Smart approvals are enabled — dangerous actions are gated automatically.
  4. Work step by step: enumerate, analyze, then act. Explain each action briefly as you go.
  5. When you have no more productive actions, summarize what you accomplished and the attack paths / findings discovered, then stop.

Begin the engagement against {host} now."""


def prepare_run(db: Session, scan_id: str, target: Target, findings: list[Finding],
                mode: str, model: str) -> dict:
    """Create the per-run Hermes home + config + task, return the streamed command.

    Returns {command, home, run_dir, task}. Does NOT execute.
    """
    home = os.path.join(_HERMES_ROOT, scan_id)
    run_dir = os.path.join(home, "workspace")
    os.makedirs(run_dir, exist_ok=True)

    ollama_url = get_setting(db, "ai_endpoint", "http://localhost:11434")
    allow_private = get_setting(db, "hermes_allow_private_urls", "true").lower() == "true"
    sandbox = get_setting(db, "hermes_sandbox", "false").lower() == "true"

    _write_config(home, run_dir, model, ollama_url, allow_private, sandbox)
    task = _build_task(target, findings, mode)

    # Persist task for reference/debugging.
    with open(os.path.join(home, "task.md"), "w") as f:
        f.write(task)

    # Env-prefixed, fully quoted command. HOME points Hermes at our generated config.
    # `chat -q` is one-shot/non-interactive; we keep tool previews (no --quiet) so the
    # agent's narrated actions stream to the transcript. Smart approvals (config) keep
    # the subprocess from blocking on a TTY.
    command = (
        f"HOME={shlex.quote(home)} "
        f"OPENAI_API_KEY=ollama "
        f"hermes chat -q {shlex.quote(task)} -m {shlex.quote(model)}"
    )
    return {"command": command, "home": home, "run_dir": run_dir, "task": task}
